//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoletoAvulsoService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntradaConsultarParcelas", Namespace="http://schemas.datacontract.org/2004/07/Servicos.Cobranca")]
    public partial class EntradaConsultarParcelas : object
    {
        
        private int VersaoField;
        
        private int codigoCotaField;
        
        private string codigoGrupoField;
        
        private string cpfCnpjField;
        
        private System.DateTime dataBaseField;
        
        private System.DateTime dataCompensacaoField;
        
        private int idCotaField;
        
        private int idEmpresaField;
        
        private int idUsuarioField;
        
        private string snUnificarParcelasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Versao
        {
            get
            {
                return this.VersaoField;
            }
            set
            {
                this.VersaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigoCota
        {
            get
            {
                return this.codigoCotaField;
            }
            set
            {
                this.codigoCotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoGrupo
        {
            get
            {
                return this.codigoGrupoField;
            }
            set
            {
                this.codigoGrupoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cpfCnpj
        {
            get
            {
                return this.cpfCnpjField;
            }
            set
            {
                this.cpfCnpjField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dataBase
        {
            get
            {
                return this.dataBaseField;
            }
            set
            {
                this.dataBaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dataCompensacao
        {
            get
            {
                return this.dataCompensacaoField;
            }
            set
            {
                this.dataCompensacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCota
        {
            get
            {
                return this.idCotaField;
            }
            set
            {
                this.idCotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmpresa
        {
            get
            {
                return this.idEmpresaField;
            }
            set
            {
                this.idEmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario
        {
            get
            {
                return this.idUsuarioField;
            }
            set
            {
                this.idUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string snUnificarParcelas
        {
            get
            {
                return this.snUnificarParcelasField;
            }
            set
            {
                this.snUnificarParcelasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoConsultarParcelas", Namespace="http://schemas.datacontract.org/2004/07/Servicos.Cobranca")]
    public partial class RetornoConsultarParcelas : object
    {
        
        private BoletoAvulsoService.ParcelaEntidadeServico[] ParcelasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BoletoAvulsoService.ParcelaEntidadeServico[] Parcelas
        {
            get
            {
                return this.ParcelasField;
            }
            set
            {
                this.ParcelasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParcelaEntidadeServico", Namespace="http://schemas.datacontract.org/2004/07/Servicos.Cobranca")]
    public partial class ParcelaEntidadeServico : object
    {
        
        private int codigoCotaField;
        
        private System.DateTime dataVencimentoField;
        
        private string historicoMovtoField;
        
        private int idCONFI008ATMPField;
        
        private int idCONFI008ATMPAgregadoField;
        
        private int identificadorBoletoField;
        
        private string numeroParcelaField;
        
        private double valorDevidoField;
        
        private double valorJurosField;
        
        private double valorMultaField;
        
        private double valorParcelaField;
        
        private int versaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigoCota
        {
            get
            {
                return this.codigoCotaField;
            }
            set
            {
                this.codigoCotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dataVencimento
        {
            get
            {
                return this.dataVencimentoField;
            }
            set
            {
                this.dataVencimentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string historicoMovto
        {
            get
            {
                return this.historicoMovtoField;
            }
            set
            {
                this.historicoMovtoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCONFI008ATMP
        {
            get
            {
                return this.idCONFI008ATMPField;
            }
            set
            {
                this.idCONFI008ATMPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCONFI008ATMPAgregado
        {
            get
            {
                return this.idCONFI008ATMPAgregadoField;
            }
            set
            {
                this.idCONFI008ATMPAgregadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int identificadorBoleto
        {
            get
            {
                return this.identificadorBoletoField;
            }
            set
            {
                this.identificadorBoletoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroParcela
        {
            get
            {
                return this.numeroParcelaField;
            }
            set
            {
                this.numeroParcelaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorDevido
        {
            get
            {
                return this.valorDevidoField;
            }
            set
            {
                this.valorDevidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorJuros
        {
            get
            {
                return this.valorJurosField;
            }
            set
            {
                this.valorJurosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorMulta
        {
            get
            {
                return this.valorMultaField;
            }
            set
            {
                this.valorMultaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorParcela
        {
            get
            {
                return this.valorParcelaField;
            }
            set
            {
                this.valorParcelaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int versao
        {
            get
            {
                return this.versaoField;
            }
            set
            {
                this.versaoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/Exceptions.Soap")]
    public partial class FaultException : object
    {
        
        private int CodeErrorField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodeError
        {
            get
            {
                return this.CodeErrorField;
            }
            set
            {
                this.CodeErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntradaMarcarParcelas", Namespace="http://schemas.datacontract.org/2004/07/Servicos.Cobranca")]
    public partial class EntradaMarcarParcelas : object
    {
        
        private int idIdentificadorField;
        
        private string pclsCONFI008ATMPField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idIdentificador
        {
            get
            {
                return this.idIdentificadorField;
            }
            set
            {
                this.idIdentificadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pclsCONFI008ATMP
        {
            get
            {
                return this.pclsCONFI008ATMPField;
            }
            set
            {
                this.pclsCONFI008ATMPField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntradaAtualizarIdentificadorBancario", Namespace="http://schemas.datacontract.org/2004/07/Servicos.Cobranca")]
    public partial class EntradaAtualizarIdentificadorBancario : object
    {
        
        private int idIdentificadorField;
        
        private int idTituloField;
        
        private string noIdentificadorField;
        
        private string stCobrancaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idIdentificador
        {
            get
            {
                return this.idIdentificadorField;
            }
            set
            {
                this.idIdentificadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTitulo
        {
            get
            {
                return this.idTituloField;
            }
            set
            {
                this.idTituloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string noIdentificador
        {
            get
            {
                return this.noIdentificadorField;
            }
            set
            {
                this.noIdentificadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stCobranca
        {
            get
            {
                return this.stCobrancaField;
            }
            set
            {
                this.stCobrancaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoAtualizarIdentificadorBancario", Namespace="http://schemas.datacontract.org/2004/07/Servicos.Cobranca")]
    public partial class RetornoAtualizarIdentificadorBancario : object
    {
        
        private string noIdentificadorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string noIdentificador
        {
            get
            {
                return this.noIdentificadorField;
            }
            set
            {
                this.noIdentificadorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntradaGerarBoleto", Namespace="http://schemas.datacontract.org/2004/07/Servicos.Cobranca")]
    public partial class EntradaGerarBoleto : object
    {
        
        private int identificadorBoletoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int identificadorBoleto
        {
            get
            {
                return this.identificadorBoletoField;
            }
            set
            {
                this.identificadorBoletoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoGerarBoleto", Namespace="http://schemas.datacontract.org/2004/07/Servicos.Cobranca")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BoletoAvulsoService.RetornoGerarBoletoDetalhado))]
    public partial class RetornoGerarBoleto : object
    {
        
        private int IDField;
        
        private string obterBoletoPDFField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string obterBoletoPDF
        {
            get
            {
                return this.obterBoletoPDFField;
            }
            set
            {
                this.obterBoletoPDFField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoGerarBoletoDetalhado", Namespace="http://schemas.datacontract.org/2004/07/Servicos.Cobranca")]
    public partial class RetornoGerarBoletoDetalhado : BoletoAvulsoService.RetornoGerarBoleto
    {
        
        private BoletoAvulsoService.DadosBoletoDetalhado dadosBoletoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BoletoAvulsoService.DadosBoletoDetalhado dadosBoleto
        {
            get
            {
                return this.dadosBoletoField;
            }
            set
            {
                this.dadosBoletoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosBoletoDetalhado", Namespace="http://schemas.datacontract.org/2004/07/Servicos.Cobranca")]
    public partial class DadosBoletoDetalhado : object
    {
        
        private string aceiteField;
        
        private string agenciaBeneficiarioField;
        
        private string dataDocumentoField;
        
        private string dataProcessamentoField;
        
        private string dataVencimentoField;
        
        private string enderecoBeneficiarioField;
        
        private string especieDocField;
        
        private string especieMoedaField;
        
        private string inscricaoNacionalBeneficiarioField;
        
        private string linhaDigitavelField;
        
        private string localPagamentoField;
        
        private string mensagemCompensaçãoField;
        
        private string nomeBeneficiarioField;
        
        private string nossoNumeroField;
        
        private string numeroCarteiraField;
        
        private string numeroDocumentoField;
        
        private string pagadorField;
        
        private int quantidadeMoerdaField;
        
        private string usoBancoField;
        
        private double valorAcrescimosField;
        
        private double valorCobradoField;
        
        private double valorDescontoField;
        
        private double valorDocumentoField;
        
        private double valorJurosField;
        
        private double valorMoedaField;
        
        private double valorMultaField;
        
        private double valorOutrasDeducoesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aceite
        {
            get
            {
                return this.aceiteField;
            }
            set
            {
                this.aceiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string agenciaBeneficiario
        {
            get
            {
                return this.agenciaBeneficiarioField;
            }
            set
            {
                this.agenciaBeneficiarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dataDocumento
        {
            get
            {
                return this.dataDocumentoField;
            }
            set
            {
                this.dataDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dataProcessamento
        {
            get
            {
                return this.dataProcessamentoField;
            }
            set
            {
                this.dataProcessamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dataVencimento
        {
            get
            {
                return this.dataVencimentoField;
            }
            set
            {
                this.dataVencimentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string enderecoBeneficiario
        {
            get
            {
                return this.enderecoBeneficiarioField;
            }
            set
            {
                this.enderecoBeneficiarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string especieDoc
        {
            get
            {
                return this.especieDocField;
            }
            set
            {
                this.especieDocField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string especieMoeda
        {
            get
            {
                return this.especieMoedaField;
            }
            set
            {
                this.especieMoedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string inscricaoNacionalBeneficiario
        {
            get
            {
                return this.inscricaoNacionalBeneficiarioField;
            }
            set
            {
                this.inscricaoNacionalBeneficiarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string linhaDigitavel
        {
            get
            {
                return this.linhaDigitavelField;
            }
            set
            {
                this.linhaDigitavelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string localPagamento
        {
            get
            {
                return this.localPagamentoField;
            }
            set
            {
                this.localPagamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensagemCompensação
        {
            get
            {
                return this.mensagemCompensaçãoField;
            }
            set
            {
                this.mensagemCompensaçãoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeBeneficiario
        {
            get
            {
                return this.nomeBeneficiarioField;
            }
            set
            {
                this.nomeBeneficiarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nossoNumero
        {
            get
            {
                return this.nossoNumeroField;
            }
            set
            {
                this.nossoNumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroCarteira
        {
            get
            {
                return this.numeroCarteiraField;
            }
            set
            {
                this.numeroCarteiraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pagador
        {
            get
            {
                return this.pagadorField;
            }
            set
            {
                this.pagadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantidadeMoerda
        {
            get
            {
                return this.quantidadeMoerdaField;
            }
            set
            {
                this.quantidadeMoerdaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usoBanco
        {
            get
            {
                return this.usoBancoField;
            }
            set
            {
                this.usoBancoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorAcrescimos
        {
            get
            {
                return this.valorAcrescimosField;
            }
            set
            {
                this.valorAcrescimosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorCobrado
        {
            get
            {
                return this.valorCobradoField;
            }
            set
            {
                this.valorCobradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorDesconto
        {
            get
            {
                return this.valorDescontoField;
            }
            set
            {
                this.valorDescontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorDocumento
        {
            get
            {
                return this.valorDocumentoField;
            }
            set
            {
                this.valorDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorJuros
        {
            get
            {
                return this.valorJurosField;
            }
            set
            {
                this.valorJurosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorMoeda
        {
            get
            {
                return this.valorMoedaField;
            }
            set
            {
                this.valorMoedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorMulta
        {
            get
            {
                return this.valorMultaField;
            }
            set
            {
                this.valorMultaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorOutrasDeducoes
        {
            get
            {
                return this.valorOutrasDeducoesField;
            }
            set
            {
                this.valorOutrasDeducoesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InGerarBoletoLance", Namespace="http://schemas.datacontract.org/2004/07/Servicos.Cobranca")]
    public partial class InGerarBoletoLance : object
    {
        
        private int idCobrancaLanceField;
        
        private int idUsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCobrancaLance
        {
            get
            {
                return this.idCobrancaLanceField;
            }
            set
            {
                this.idCobrancaLanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario
        {
            get
            {
                return this.idUsuarioField;
            }
            set
            {
                this.idUsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutGerarBoletoLance", Namespace="http://schemas.datacontract.org/2004/07/Servicos.Cobranca")]
    public partial class OutGerarBoletoLance : object
    {
        
        private int idField;
        
        private string obterBoletoPDFField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string obterBoletoPDF
        {
            get
            {
                return this.obterBoletoPDFField;
            }
            set
            {
                this.obterBoletoPDFField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntradaBoletoCobranca", Namespace="http://schemas.datacontract.org/2004/07/Servicos.Cobranca")]
    public partial class EntradaBoletoCobranca : object
    {
        
        private string cpfCnpjField;
        
        private int idCobrancaField;
        
        private int idCotaField;
        
        private int idUsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cpfCnpj
        {
            get
            {
                return this.cpfCnpjField;
            }
            set
            {
                this.cpfCnpjField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCobranca
        {
            get
            {
                return this.idCobrancaField;
            }
            set
            {
                this.idCobrancaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCota
        {
            get
            {
                return this.idCotaField;
            }
            set
            {
                this.idCotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario
        {
            get
            {
                return this.idUsuarioField;
            }
            set
            {
                this.idUsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoGerarBoletoCobranca", Namespace="http://schemas.datacontract.org/2004/07/Servicos.Cobranca")]
    public partial class RetornoGerarBoletoCobranca : object
    {
        
        private int IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntradaConsultarParcelasAVencer", Namespace="http://schemas.datacontract.org/2004/07/Servicos.Cobranca")]
    public partial class EntradaConsultarParcelasAVencer : object
    {
        
        private string cpfCnpjField;
        
        private System.DateTime dataBaseField;
        
        private int idEmpresaField;
        
        private int idUsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cpfCnpj
        {
            get
            {
                return this.cpfCnpjField;
            }
            set
            {
                this.cpfCnpjField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dataBase
        {
            get
            {
                return this.dataBaseField;
            }
            set
            {
                this.dataBaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmpresa
        {
            get
            {
                return this.idEmpresaField;
            }
            set
            {
                this.idEmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario
        {
            get
            {
                return this.idUsuarioField;
            }
            set
            {
                this.idUsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoConsultarParcelasAVencer", Namespace="http://schemas.datacontract.org/2004/07/Servicos.Cobranca")]
    public partial class RetornoConsultarParcelasAVencer : object
    {
        
        private BoletoAvulsoService.ParcelaAVEntidadeServico[] ParcelasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BoletoAvulsoService.ParcelaAVEntidadeServico[] Parcelas
        {
            get
            {
                return this.ParcelasField;
            }
            set
            {
                this.ParcelasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParcelaAVEntidadeServico", Namespace="http://schemas.datacontract.org/2004/07/Servicos.Cobranca")]
    public partial class ParcelaAVEntidadeServico : object
    {
        
        private int codigoCotaField;
        
        private int codigoGrupoField;
        
        private System.DateTime dataVencimentoField;
        
        private string dddField;
        
        private string emailField;
        
        private string historicoMovtoField;
        
        private int idCONFI008ATMPField;
        
        private int idCONFI008ATMPAgregadoField;
        
        private int idEmailField;
        
        private int idTelefoneField;
        
        private int identificadorBoletoField;
        
        private string numeroParcelaField;
        
        private string telefoneField;
        
        private double valorDevidoField;
        
        private double valorJurosField;
        
        private double valorMultaField;
        
        private double valorParcelaField;
        
        private int versaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigoCota
        {
            get
            {
                return this.codigoCotaField;
            }
            set
            {
                this.codigoCotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigoGrupo
        {
            get
            {
                return this.codigoGrupoField;
            }
            set
            {
                this.codigoGrupoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dataVencimento
        {
            get
            {
                return this.dataVencimentoField;
            }
            set
            {
                this.dataVencimentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ddd
        {
            get
            {
                return this.dddField;
            }
            set
            {
                this.dddField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string historicoMovto
        {
            get
            {
                return this.historicoMovtoField;
            }
            set
            {
                this.historicoMovtoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCONFI008ATMP
        {
            get
            {
                return this.idCONFI008ATMPField;
            }
            set
            {
                this.idCONFI008ATMPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCONFI008ATMPAgregado
        {
            get
            {
                return this.idCONFI008ATMPAgregadoField;
            }
            set
            {
                this.idCONFI008ATMPAgregadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmail
        {
            get
            {
                return this.idEmailField;
            }
            set
            {
                this.idEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTelefone
        {
            get
            {
                return this.idTelefoneField;
            }
            set
            {
                this.idTelefoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int identificadorBoleto
        {
            get
            {
                return this.identificadorBoletoField;
            }
            set
            {
                this.identificadorBoletoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroParcela
        {
            get
            {
                return this.numeroParcelaField;
            }
            set
            {
                this.numeroParcelaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefone
        {
            get
            {
                return this.telefoneField;
            }
            set
            {
                this.telefoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorDevido
        {
            get
            {
                return this.valorDevidoField;
            }
            set
            {
                this.valorDevidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorJuros
        {
            get
            {
                return this.valorJurosField;
            }
            set
            {
                this.valorJurosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorMulta
        {
            get
            {
                return this.valorMultaField;
            }
            set
            {
                this.valorMultaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorParcela
        {
            get
            {
                return this.valorParcelaField;
            }
            set
            {
                this.valorParcelaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int versao
        {
            get
            {
                return this.versaoField;
            }
            set
            {
                this.versaoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntradaGerarBoletoPDFeSMS", Namespace="http://schemas.datacontract.org/2004/07/Servicos.Cobranca")]
    public partial class EntradaGerarBoletoPDFeSMS : object
    {
        
        private int identificadorBoletoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int identificadorBoleto
        {
            get
            {
                return this.identificadorBoletoField;
            }
            set
            {
                this.identificadorBoletoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoGerarBoletoPDFeSMS", Namespace="http://schemas.datacontract.org/2004/07/Servicos.Cobranca")]
    public partial class RetornoGerarBoletoPDFeSMS : object
    {
        
        private int IDField;
        
        private string obterBoletoPDFField;
        
        private string obterLinhaDigitavelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string obterBoletoPDF
        {
            get
            {
                return this.obterBoletoPDFField;
            }
            set
            {
                this.obterBoletoPDFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string obterLinhaDigitavel
        {
            get
            {
                return this.obterLinhaDigitavelField;
            }
            set
            {
                this.obterLinhaDigitavelField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntradaGerarBoletoBD", Namespace="http://schemas.datacontract.org/2004/07/Servicos.Cobranca")]
    public partial class EntradaGerarBoletoBD : object
    {
        
        private int idUsuarioField;
        
        private int identificadorBoletoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario
        {
            get
            {
                return this.idUsuarioField;
            }
            set
            {
                this.idUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int identificadorBoleto
        {
            get
            {
                return this.identificadorBoletoField;
            }
            set
            {
                this.identificadorBoletoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BoletoAvulsoService.IBoletoAvulsoService")]
    public interface IBoletoAvulsoService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoletoAvulsoService/ConsultarParcelas", ReplyAction="http://tempuri.org/IBoletoAvulsoService/ConsultarParcelasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BoletoAvulsoService.FaultException), Action="http://tempuri.org/IBoletoAvulsoService/ConsultarParcelasFaultExceptionFaul" +
            "t", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/Exceptions.Soap")]
        System.Threading.Tasks.Task<BoletoAvulsoService.RetornoConsultarParcelas> ConsultarParcelasAsync(BoletoAvulsoService.EntradaConsultarParcelas Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoletoAvulsoService/MarcarParcela", ReplyAction="http://tempuri.org/IBoletoAvulsoService/MarcarParcelaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BoletoAvulsoService.FaultException), Action="http://tempuri.org/IBoletoAvulsoService/MarcarParcelaFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/Exceptions.Soap")]
        System.Threading.Tasks.Task MarcarParcelaAsync(BoletoAvulsoService.EntradaMarcarParcelas Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoletoAvulsoService/AtualizarIdentificadorBancario", ReplyAction="http://tempuri.org/IBoletoAvulsoService/AtualizarIdentificadorBancarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BoletoAvulsoService.FaultException), Action="http://tempuri.org/IBoletoAvulsoService/AtualizarIdentificadorBancarioFault" +
            "ExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/Exceptions.Soap")]
        System.Threading.Tasks.Task<BoletoAvulsoService.RetornoAtualizarIdentificadorBancario> AtualizarIdentificadorBancarioAsync(BoletoAvulsoService.EntradaAtualizarIdentificadorBancario Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoletoAvulsoService/GerarBoleto", ReplyAction="http://tempuri.org/IBoletoAvulsoService/GerarBoletoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BoletoAvulsoService.FaultException), Action="http://tempuri.org/IBoletoAvulsoService/GerarBoletoFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/Exceptions.Soap")]
        System.Threading.Tasks.Task<BoletoAvulsoService.RetornoGerarBoleto> GerarBoletoAsync(BoletoAvulsoService.EntradaGerarBoleto Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoletoAvulsoService/GerarBoletoLance", ReplyAction="http://tempuri.org/IBoletoAvulsoService/GerarBoletoLanceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BoletoAvulsoService.FaultException), Action="http://tempuri.org/IBoletoAvulsoService/GerarBoletoLanceFaultExceptionFault" +
            "", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/Exceptions.Soap")]
        System.Threading.Tasks.Task<BoletoAvulsoService.OutGerarBoletoLance> GerarBoletoLanceAsync(BoletoAvulsoService.InGerarBoletoLance Entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoletoAvulsoService/GerarBoletoCobranca", ReplyAction="http://tempuri.org/IBoletoAvulsoService/GerarBoletoCobrancaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BoletoAvulsoService.FaultException), Action="http://tempuri.org/IBoletoAvulsoService/GerarBoletoCobrancaFaultExceptionFa" +
            "ult", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/Exceptions.Soap")]
        System.Threading.Tasks.Task<BoletoAvulsoService.RetornoGerarBoletoCobranca> GerarBoletoCobrancaAsync(BoletoAvulsoService.EntradaBoletoCobranca Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoletoAvulsoService/ConsultarParcelasAVencer", ReplyAction="http://tempuri.org/IBoletoAvulsoService/ConsultarParcelasAVencerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BoletoAvulsoService.FaultException), Action="http://tempuri.org/IBoletoAvulsoService/ConsultarParcelasAVencerFaultExcept" +
            "ionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/Exceptions.Soap")]
        System.Threading.Tasks.Task<BoletoAvulsoService.RetornoConsultarParcelasAVencer> ConsultarParcelasAVencerAsync(BoletoAvulsoService.EntradaConsultarParcelasAVencer Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoletoAvulsoService/GerarBoletoPDFeSMS", ReplyAction="http://tempuri.org/IBoletoAvulsoService/GerarBoletoPDFeSMSResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BoletoAvulsoService.FaultException), Action="http://tempuri.org/IBoletoAvulsoService/GerarBoletoPDFeSMSFaultExceptionFau" +
            "lt", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/Exceptions.Soap")]
        System.Threading.Tasks.Task<BoletoAvulsoService.RetornoGerarBoletoPDFeSMS> GerarBoletoPDFeSMSAsync(BoletoAvulsoService.EntradaGerarBoletoPDFeSMS Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoletoAvulsoService/GerarBoletoBD", ReplyAction="http://tempuri.org/IBoletoAvulsoService/GerarBoletoBDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BoletoAvulsoService.FaultException), Action="http://tempuri.org/IBoletoAvulsoService/GerarBoletoBDFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/Exceptions.Soap")]
        System.Threading.Tasks.Task<BoletoAvulsoService.RetornoGerarBoleto> GerarBoletoBDAsync(BoletoAvulsoService.EntradaGerarBoletoBD Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoletoAvulsoService/GerarBoletoDetalhado", ReplyAction="http://tempuri.org/IBoletoAvulsoService/GerarBoletoDetalhadoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BoletoAvulsoService.FaultException), Action="http://tempuri.org/IBoletoAvulsoService/GerarBoletoDetalhadoFaultExceptionF" +
            "ault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/Exceptions.Soap")]
        System.Threading.Tasks.Task<BoletoAvulsoService.RetornoGerarBoletoDetalhado> GerarBoletoDetalhadoAsync(BoletoAvulsoService.EntradaGerarBoleto Entrada);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IBoletoAvulsoServiceChannel : BoletoAvulsoService.IBoletoAvulsoService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class BoletoAvulsoServiceClient : System.ServiceModel.ClientBase<BoletoAvulsoService.IBoletoAvulsoService>, BoletoAvulsoService.IBoletoAvulsoService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BoletoAvulsoServiceClient() : 
                base(BoletoAvulsoServiceClient.GetDefaultBinding(), BoletoAvulsoServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IBoletoAvulsoService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BoletoAvulsoServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(BoletoAvulsoServiceClient.GetBindingForEndpoint(endpointConfiguration), BoletoAvulsoServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BoletoAvulsoServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BoletoAvulsoServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BoletoAvulsoServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BoletoAvulsoServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BoletoAvulsoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<BoletoAvulsoService.RetornoConsultarParcelas> ConsultarParcelasAsync(BoletoAvulsoService.EntradaConsultarParcelas Request)
        {
            return base.Channel.ConsultarParcelasAsync(Request);
        }
        
        public System.Threading.Tasks.Task MarcarParcelaAsync(BoletoAvulsoService.EntradaMarcarParcelas Request)
        {
            return base.Channel.MarcarParcelaAsync(Request);
        }
        
        public System.Threading.Tasks.Task<BoletoAvulsoService.RetornoAtualizarIdentificadorBancario> AtualizarIdentificadorBancarioAsync(BoletoAvulsoService.EntradaAtualizarIdentificadorBancario Request)
        {
            return base.Channel.AtualizarIdentificadorBancarioAsync(Request);
        }
        
        public System.Threading.Tasks.Task<BoletoAvulsoService.RetornoGerarBoleto> GerarBoletoAsync(BoletoAvulsoService.EntradaGerarBoleto Request)
        {
            return base.Channel.GerarBoletoAsync(Request);
        }
        
        public System.Threading.Tasks.Task<BoletoAvulsoService.OutGerarBoletoLance> GerarBoletoLanceAsync(BoletoAvulsoService.InGerarBoletoLance Entrada)
        {
            return base.Channel.GerarBoletoLanceAsync(Entrada);
        }
        
        public System.Threading.Tasks.Task<BoletoAvulsoService.RetornoGerarBoletoCobranca> GerarBoletoCobrancaAsync(BoletoAvulsoService.EntradaBoletoCobranca Request)
        {
            return base.Channel.GerarBoletoCobrancaAsync(Request);
        }
        
        public System.Threading.Tasks.Task<BoletoAvulsoService.RetornoConsultarParcelasAVencer> ConsultarParcelasAVencerAsync(BoletoAvulsoService.EntradaConsultarParcelasAVencer Request)
        {
            return base.Channel.ConsultarParcelasAVencerAsync(Request);
        }
        
        public System.Threading.Tasks.Task<BoletoAvulsoService.RetornoGerarBoletoPDFeSMS> GerarBoletoPDFeSMSAsync(BoletoAvulsoService.EntradaGerarBoletoPDFeSMS Request)
        {
            return base.Channel.GerarBoletoPDFeSMSAsync(Request);
        }
        
        public System.Threading.Tasks.Task<BoletoAvulsoService.RetornoGerarBoleto> GerarBoletoBDAsync(BoletoAvulsoService.EntradaGerarBoletoBD Request)
        {
            return base.Channel.GerarBoletoBDAsync(Request);
        }
        
        public System.Threading.Tasks.Task<BoletoAvulsoService.RetornoGerarBoletoDetalhado> GerarBoletoDetalhadoAsync(BoletoAvulsoService.EntradaGerarBoleto Entrada)
        {
            return base.Channel.GerarBoletoDetalhadoAsync(Entrada);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBoletoAvulsoService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBoletoAvulsoService))
            {
                return new System.ServiceModel.EndpointAddress("http://example.com" +
                        "ervice.svc");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BoletoAvulsoServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IBoletoAvulsoService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BoletoAvulsoServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IBoletoAvulsoService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IBoletoAvulsoService,
        }
    }
}
