//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace exp.dados
{
    public partial class pesquisa_perguntas
    {
        public pesquisa_perguntas()
        {
            pesquisa_resultados = new HashSet<pesquisa_resultados>();
            pesquisa_respostas = new HashSet<pesquisa_respostas>();
        }

        public int id { get; set; }

        public int tipos_id { get; set; }

        [Required]
        [StringLength(255)]
        public string pergunta { get; set; }

        public DateTime? criadaem { get; set; }

        public int ordem { get; set; }

        public virtual ICollection<pesquisa_resultados> pesquisa_resultados { get; set; }

        public virtual ICollection<pesquisa_respostas> pesquisa_respostas { get; set; }

        public virtual pesquisa_tipos pesquisa_tipos { get; set; }
    }
}
