//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace exp.dados
{
    public partial class pesquisa_clientes
    {
        public int id { get; set; }

        public int? tipos_id { get; set; }

        [StringLength(10)]
        public string grupo { get; set; }

        [StringLength(10)]
        public string cota { get; set; }

        [StringLength(12)]
        public string v { get; set; }

        [StringLength(180)]
        public string nome { get; set; }

        [StringLength(30)]
        public string codigo { get; set; }

        [Column(TypeName = "date")]
        public DateTime? dt_vena { get; set; }

        [Column(TypeName = "date")]
        public DateTime? dt_entrega { get; set; }

        [StringLength(180)]
        public string email { get; set; }

        [StringLength(150)]
        public string equipe { get; set; }

        [StringLength(150)]
        public string scp { get; set; }

        [StringLength(30)]
        public string codigoep { get; set; }

        [StringLength(150)]
        public string empresaparceira { get; set; }


        public int empresa_id { get; set; }
        
        public DateTime? dt_envio { get; set; }

        public DateTime? dt_cadastro { get; set; }

        public bool lido { get; set; }

        public pesquisa_clientes()
        {
            pesquisa_resultados = new HashSet<pesquisa_resultados>();
        }

        
        public virtual ICollection<pesquisa_resultados> pesquisa_resultados { get; set; }

    
    }
}
