//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace exp.dados
{
    public partial class pesquisa_tipos
    {
       public pesquisa_tipos()
        {
            pesquisa_perguntas = new HashSet<pesquisa_perguntas>();
            pesquisa_resultados = new HashSet<pesquisa_resultados>();
        }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int id { get; set; }

        [StringLength(50)]
        public string tipo { get; set; }

        [StringLength(50)]
        public string permalink { get; set; }

        public virtual ICollection<pesquisa_perguntas> pesquisa_perguntas { get; set; }

        public virtual ICollection<pesquisa_resultados> pesquisa_resultados { get; set; }
    }
}
