//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace exp.dados
{
    public partial class pesquisa_respostas
    {
        public pesquisa_respostas()
        {
            pesquisa_resultados = new HashSet<pesquisa_resultados>();
        }

        public int id { get; set; }

        public int perguntas_id { get; set; }

        [Required]
        [StringLength(255)]
        public string resposta { get; set; }

        public DateTime? criadaem { get; set; }

        public bool qual { get; set; }

        public int ordem { get; set; }

        public virtual pesquisa_perguntas pesquisa_perguntas { get; set; }

        public virtual ICollection<pesquisa_resultados> pesquisa_resultados { get; set; }
    }
}
