//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace exp.dados
{
    public partial class pesquisa_resultados
    {
        [Key]
        [Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int perguntas_id { get; set; }

        [Key]
        [Column(Order = 1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int resposta_id { get; set; }

        [Key]
        [Column(Order = 2)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int cliente_id { get; set; }

        [Key]
        [Column(Order = 3)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int tipos_id { get; set; }

        [Key]
        [Column(Order = 4)]
        [StringLength(10)]
        public string grupo { get; set; }

        [Key]
        [Column(Order = 5)]
        [StringLength(10)]
        public string cota { get; set; }

        public int? site_id { get; set; }

        public DateTime dt { get; set; }

        [StringLength(100)]
        public string qual { get; set; }

        public virtual pesquisa_perguntas pesquisa_perguntas { get; set; }

        public virtual pesquisa_respostas pesquisa_respostas { get; set; }

        public virtual site site { get; set; }

        public virtual pesquisa_tipos pesquisa_tipos { get; set; }

        public virtual pesquisa_clientes pesquisa_clientes { get; set; }
    }
}
